version: '3'
services:
  pgsql:
    image: postgres:13.6-alpine
    environment:
      POSTGRES_USER: receituarios
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: receituarios_production
    volumes:
      - pgsql-data:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - RAILS_ENV=production
volumes:
  pgsql-data:
