# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5985018bfa476c0458f74643e83c4d7cfc641822dba8783237f2e9656ac56485b1e7dc3f86338ce5cb5ba477e61ceffd7884bbebea03c235837447064b2ae51

test:
  secret_key_base: cad2f57216f67cd94942b70351167d31e0b1060a5f21d9d192a1ae71bd91277e88a7f1c9e3293b27897ea3d0bd9f03d8c44395e2666213f537ee2dd112897b23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
